####
# https://quarkus.io/guides/building-native-image#multistage-docker
#
# To build the image run:
#
# docker build -f src/main/docker/Dockerfile.native-micro-multistage -t quarkus/mflow-crud-native-micro .
#
# Then run the container using:
#
# docker run -i --rm -p 8080:8080 quarkus/mflow-crud-native-micro
###

## Stage 1 : build with maven builder image with native capabilities
FROM quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-21 AS build
COPY --chown=quarkus:quarkus mvnw /usr/src/app/mvnw
COPY --chown=quarkus:quarkus .mvn /usr/src/app/.mvn
COPY --chown=quarkus:quarkus pom.xml /usr/src/app/
USER quarkus
WORKDIR /usr/src/app
RUN ./mvnw -B org.apache.maven.plugins:maven-dependency-plugin:3.1.2:go-offline
COPY src /usr/src/app/src
RUN ./mvnw package -Dnative

## Stage 2 : create the docker final image
FROM quay.io/quarkus/quarkus-micro-image:2.0
WORKDIR /opt/app/
COPY --from=build /usr/src/app/target/*-runner /opt/app/application

# Set up permissions for user `1001`
RUN chmod 775 /opt/app /opt/app/application \
  && chown -R 1001 /opt/app \
  && chmod -R "g+rwX" /opt/app \
  && chown -R 1001:root /opt/app

EXPOSE 8080
USER 1001

CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]